version: '2'
services:

##### work container #####
  workspace:
    build:
      context: ./workspace
    tty: true

##### php-fpm container #####
  php-fpm:
    build:
      context: ./php-fpm
    ports:
      - "9000"
    volumes:
      - ./logs/php-fpm:/var/log/

##### nginx container #####
  nginx:
    build:
      context: ./nginx
#      args:
#        - PHP_UPSTREAM=php-fpm
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./workspace/app:/var/www
    ports:
      - "8080:80"
    links:
      - php-fpm

##### mysql container #####
  mysql:
    build: ./mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

##### phpmyadmin container #####
  phpmyadmin:
    build: ./phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    links:
      - "mysql:db"

###### redis container #####
  redis:
    build: ./redis
    volumes:
      - ./data/redis:/data
      - ./redis/conf:/etc/reids
    ports:
      - "6379:6379"

##### mongodb container #####
  mongodb:
    build: ./mongodb
    ports:
      - "28017:28017"
      - "27017:27017"
    environment:
      AUTH: 'no'
      MONGODB_USER: docker
      MONGODB_DATABASE: docker
      MONGODB_PASS: secret
    volumes:
      - ./data/mongodb:/data/db