version: '2'
services:

##### work container #####
  workspace:
    build:
      context: ./workspace
    tty: true

##### php-fpm container #####
  php-fpm:
    build:
      context: ./php-fpm
    ports:
      - "9000"
    volumes:
      - ./logs/php-fpm:/var/log/
      - ./workspace/app:/var/www

##### nginx container #####
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM=php-fpm
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./workspace/app:/var/www
    ports:
      - "8080:80"
    links:
      - php-fpm

##### mysql container #####
  mysql:
    build: ./mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

##### postgresql container #####
  postgresql:
    build: ./postgresql
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: secret

##### phpmyadmin container #####
  phpmyadmin:
    build: ./phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/phpmyadmin:/sessions
    ports:
      - "8081:80"
    links:
      - "mysql:db"

##### pgadmin container #####
  pgadmin:
    build: ./pgadmin
    ports:
      - "5650:5650"
    links:
      - postgresql

###### redis container #####
  redis:
    build: ./redis
    volumes:
      - ./data/redis:/data
      - ./redis/conf:/etc/reids
    ports:
      - "6379:6379"

##### mongodb container #####
  mongodb:
    build: ./mongodb
    ports:
      - "28017:28017"
      - "26017:27017"
    volumes:
      - ./data/mongodb:/data/db
      - ./logs/mongodb:/var/log/mongodb

##### rabbitmq container #####
  rabbitmq:
    build: ./rabbitmq
    ports:
      - "5672:5672"
      - "15671:15671"
      - "8088:15672"
    privileged: true
    volumes:
      - ./data/rabbitmq:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: docker
      RABBITMQ_DEFAULT_PASS: secret
    # links:
    #   - php-fpm

##### elasticsearch container #####
  elasticsearch:
    build: ./elasticsearch
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch/conf:/usr/share/elasticsearch/config
      - ./data/elasticsearch:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"
    # links:
    #   - php-fpm
